---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install AWS CLI
      dnf:
        name: awscli
        state: present

    - name: Install EFS Mount Helper
      dnf:
        name: amazon-efs-utils
        state: present

    - name: Install Java 17
      dnf:
        name: java-17-amazon-corretto
        state: present

    - name: Install Java 17 Development Kit
      dnf:
        name: java-17-amazon-corretto-devel
        state: present

    - name: Add Jenkins repository
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
      args:
        creates: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins repository key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins

    - name: Install jenkins
      dnf:
        name: jenkins
        state: present

    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes