---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: install efs mount helper
      dnf:
        name: amazon-efs-utils
        state: present

    - name: install aws cli
      dnf:
        name: awscli
        state: present

    - name: install java 17
      dnf:
        name: java-17-amazon-corretto
        state: present

    - name: add jenkins repository
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
      args:
        creates: /etc/yum.repos.d/jenkins.repo

    - name: import jenkins repository key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins

    - name: install jenkins
      dnf:
        name: jenkins
        state: present

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: enable Jenkins service
      systemd:
        name: jenkins
        state: enabled
        enabled: yes

    - name: start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes

    - name: just force systemd to re-execute itself (2.8 and above)
      systemd:
        daemon_reexec: yes
