---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update YUM Packages
      yum:
        name: '*'
        state: latest

    - name: Install Git, Wget & Unzip
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - wget
        - unzip

    - name: Install Java
      dnf:
        name: java-17-amazon-corretto
        state: present
    
    - name: Install Python3, Pip3
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - python3
        - python3-pip

    - name: Install AWS CLI
      yum:
        name: awscli
        state: present

    - name: Add Jenkins repository
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
      args:
        creates: /etc/yum.repos.d/jenkins.repo

    - name: Add Jenkins repository key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Install EFS
      yum:
        name: nfs-utils
        state: present

    - name: Upgrade YUM Packages
      command: yum upgrade -y