name: Terraform Apply

on:
  push:
    branches:
      - "**"
      - "!main"
    path:
      - "infra/*"

  pull_request:
    paths:
      - "infra/*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4
          terraform_wrapper: false # Optional: Skip the wrapper script

      - name: Initialize
        run: terraform init

      - name: Format
        with:
          command: if [ -n "$(terraform fmt -check -recursive)" ]; then echo "Terraform files must be formatted. Please run terraform fmt to fix the formatting issues and commit the changes."; exit 1; fi


      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan